"""
导出工具

对比图拼接 + 批量 CSV/HTML 报告导出。
"""
import csv
import logging
import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

import cv2
import numpy as np

logger = logging.getLogger(__name__)


def export_comparison(original: np.ndarray, enhanced: np.ndarray,
                      output_path: Path, layout: str = "horizontal") -> bool:
    """
    拼接原图和增强图为一张对比图并保存。

    Args:
        original: 原图 (H, W, C) uint8
        enhanced: 增强图 (H, W, C) uint8
        output_path: 输出路径
        layout: "horizontal"(左右) / "vertical"(上下) / "split"(带分割线)
    """
    try:
        # 统一尺寸
        h = max(original.shape[0], enhanced.shape[0])
        w = max(original.shape[1], enhanced.shape[1])
        orig_resized = cv2.resize(original, (w, h))
        enh_resized = cv2.resize(enhanced, (w, h))

        # 颜色空间
        if len(orig_resized.shape) == 2:
            orig_resized = cv2.cvtColor(orig_resized, cv2.COLOR_GRAY2BGR)
        elif orig_resized.shape[2] == 4:
            orig_resized = orig_resized[:, :, :3]
        if len(enh_resized.shape) == 2:
            enh_resized = cv2.cvtColor(enh_resized, cv2.COLOR_GRAY2BGR)
        elif enh_resized.shape[2] == 4:
            enh_resized = enh_resized[:, :, :3]

        # 标签
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(orig_resized, "Original", (10, 30), font, 0.8, (255, 255, 255), 2)
        cv2.putText(enh_resized, "Enhanced", (10, 30), font, 0.8, (255, 255, 255), 2)

        if layout == "horizontal":
            # 中间分隔线
            result = np.hstack([orig_resized, enh_resized])
            cv2.line(result, (w, 0), (w, h), (255, 255, 255), 2)
        elif layout == "vertical":
            result = np.vstack([orig_resized, enh_resized])
            cv2.line(result, (0, h), (w, h), (255, 255, 255), 2)
        else:  # split
            result = np.hstack([orig_resized, enh_resized])
            cv2.line(result, (w, 0), (w, h), (255, 255, 255), 2)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        bgr = cv2.cvtColor(result, cv2.COLOR_RGB2BGR)
        cv2.imwrite(str(output_path), bgr)
        logger.info(f"对比图已导出: {output_path}")
        return True
    except Exception as e:
        logger.error(f"对比图导出失败: {e}")
        return False


def export_batch_report(results: List[Dict[str, Any]], output_path: Path,
                        format: str = "csv") -> bool:
    """
    导出批量处理指标报告。

    Args:
        results: [{"file": str, "uiqm": float, "psnr": float, ...}, ...]
        output_path: 输出路径
        format: "csv" / "html"
    """
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        if format == "csv":
            return _export_csv(results, output_path)
        elif format == "html":
            return _export_html(results, output_path)
        else:
            logger.error(f"不支持的报告格式: {format}")
            return False
    except Exception as e:
        logger.error(f"报告导出失败: {e}")
        return False


def _export_csv(results: List[Dict[str, Any]], path: Path) -> bool:
    """导出 CSV 格式报告"""
    if not results:
        logger.warning("没有可导出的结果")
        return False
    keys = list(results[0].keys())
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(results)
    logger.info(f"CSV报告已导出: {path}")
    return True


def _export_html(results: List[Dict[str, Any]], path: Path) -> bool:
    """导出 HTML 格式报告"""
    if not results:
        return False
    keys = list(results[0].keys())
    rows_html = ""
    for r in results:
        row = "".join(f"<td>{r.get(k, '')}</td>" for k in keys)
        rows_html += f"<tr>{row}</tr>\n"

    head = "".join(f"<th>{k}</th>" for k in keys)
    html = f"""<!DOCTYPE html>
<html lang="zh">
<head><meta charset="utf-8"><title>Batch Report</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; margin: 20px; background: #f5f5f5; }}
h2 {{ color: #333; }}
table {{ border-collapse: collapse; width: 100%%; background: #fff; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
th {{ background: #0078d4; color: #fff; padding: 10px 14px; text-align: left; }}
td {{ padding: 8px 14px; border-bottom: 1px solid #eee; }}
tr:hover {{ background: #f0f8ff; }}
.footer {{ color: #999; margin-top: 20px; font-size: 12px; }}
</style></head>
<body>
<h2>Batch Processing Report</h2>
<p>Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Total: {len(results)} images</p>
<table><thead><tr>{head}</tr></thead><tbody>{rows_html}</tbody></table>
<p class="footer">Generated by FUnIE-GAN</p>
</body></html>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    logger.info(f"HTML报告已导出: {path}")
    return True


def compute_batch_metrics(original_path: str, enhanced_path: str) -> Dict[str, Any]:
    """计算单张图的批量指标"""
    from ..core.metrics import ImageMetrics
    from ..utils.file_io import read_image

    orig = read_image(original_path)
    enh = read_image(enhanced_path)

    m = ImageMetrics()
    metrics = m.evaluate(orig, enh)

    return {
        "file": Path(original_path).name,
        "uiqm": round(metrics.uiqm, 4),
        "uism": round(metrics.uism, 4),
        "uiconm": round(metrics.uiconm, 4),
        "ssim": round(metrics.ssim, 4),
        "psnr": round(metrics.psnr, 2),
        "mae": round(metrics.mae, 4),
        "uciqe": round(metrics.uciqe, 4),
    }
